# This is a config for E2B sandbox template.
# You can use template ID (x120mirscqzatp2as8y4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("x120mirscqzatp2as8y4") # Sync sandbox
# sandbox = await AsyncSandbox.create("x120mirscqzatp2as8y4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('x120mirscqzatp2as8y4')

team_id = "ad70b2f9-0afd-4be1-a8d0-475e66fbaedb"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "x120mirscqzatp2as8y4"
