# This is a config for E2B sandbox template.
# You can use template ID (flt8m6oaxza6b7ybia3w) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("flt8m6oaxza6b7ybia3w") # Sync sandbox
# sandbox = await AsyncSandbox.create("flt8m6oaxza6b7ybia3w") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('flt8m6oaxza6b7ybia3w')

team_id = "ad70b2f9-0afd-4be1-a8d0-475e66fbaedb"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "flt8m6oaxza6b7ybia3w"
